spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


app.admin.username=RyPel13
app.admin.password=MesutOzil@123
app.jwt.secret=F8h89xLq2vB7yN9zA3uP5rE1nK0mJ6oW
app.jwt.expiration=86400000